name: warthog_flutter_wallet
description: A Warthog cryptocurrency wallet for iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Notifikime
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.4
  permission_handler: ^11.0.0
  
  # Kripto dhe wallet
  bip39: ^1.0.6
  bip32: ^2.0.0
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  convert: ^3.1.1
  hex: ^0.2.0
  fixnum: ^1.0.1
  
  # Networking
  http: ^1.2.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  file_picker: ^5.3.0
  share_plus: ^7.2.2
  path_provider: ^2.0.15
  
  # UI
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  
  # Siguri
  encrypt: ^5.0.3
  local_auth: ^2.1.6
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# Konfigurimi për ikonën e aplikacionit
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/warthog_logo.png"  # Ndrysho këtu
  adaptive_icon_background: "#F25C05"
  remove_alpha_ios: true